development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: hcdesignsby@gmail.com
  :password: brandingforpizza01
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: hcdesignsby@gmail.com
  :password: brandingforpizza01
  :enable_starttls_auto: true
